global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'broker'
    static_configs:
      - targets: ['broker:1883']


  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'alertmanager'
    static_configs:
        - targets: [ 'alertmanager:9093' ]

rule_files:
  - 'alert.rules.yml'

alerting:
    alertmanagers:
      - static_configs:
          - targets:
              - 'alertmanager:9093'